### ISSUE TITLE
UDF Failed to execute health check for long running task

### ISSUE THREAD

**Issue by alexanghh** [numaproj/numaflow-python#32]
**Describe the bug**

UDF processed msg but fails to update numaflow (i.e. msg counter does not decrease in numaflow ui and the next vertice does not receive the msg)
This happens to long running job and on large batch size

- long running job: curl ~15mb file from internet and upload to S3
- batch size: default (initial msg count of 100)

**To Reproduce**

1. send url list to http source 
2. http source -> split vertice (split list to individual url msg)
3. split vertice -> download vertice (download url and upload to s3)
4. download vertice -> log sink (print downloaded url)

**Expected behavior**
download vertice should 
- successfully download url and upload to s3
- send msg to log sink 
- reduce Ack Pending

**Screenshots**
Logs from UDF pod numa as follows:
`+ python main.py
GRPC Server listening on: unix:///var/run/numaflow/function.sock with max threads: 96
downloading: {"playlist": "XXX", "file_url": "https://xxxxx"}`

Logs from UDF pod numa as follows:
```kubectl logs playlist-dowload-download-save-0-szj16 numa
{"level":"info","ts":1670137326.7446299,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.74482,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.756047,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7560985,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7569191,"logger":"numaflow.MapUDF-processor","caller":"fetch/edge_fetcher.go:46","msg":"Creating a new edge watermark fetcher","vertex":"playlist-dowload-download-save","bufferName":"default-playlist-dowload-list-playlist-download-save"}
{"level":"info","ts":1670137326.756994,"logger":"numaflow.MapUDF-processor","caller":"fetch/processor_manager.go:117","msg":"Refreshing ActiveProcessors ticker started","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.75954,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7596073,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.759695,"logger":"numaflow.MapUDF-processor","caller":"fetch/processor_manager.go:184","msg":"v.AddProcessor successfully added a new fromProcessor","vertex":"playlist-dowload-download-save","fromProcessor":"playlist-dowload-list-playlist-0"}
{"level":"info","ts":1670137326.7621307,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.762229,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.762889,"logger":"numaflow.MapUDF-processor","caller":"publish/publisher.go:61","msg":"Creating a new watermark publisher","vertex":"playlist-dowload-download-save","entityID":"playlist-dowload-download-save-0","otStore":"playlist-dowload-default-playlist-dowload-download-save-log-output_OT","hbStore":"playlist-dowload-default-playlist-dowload-download-save-log-output_PROCESSORS"}
{"level":"warn","ts":1670137326.7631323,"logger":"numaflow.MapUDF-processor","caller":"publish/publisher.go:154","msg":"Unable to load latest watermark from ot store (failed to get value from ot store)","vertex":"playlist-dowload-download-save","entityID":"playlist-dowload-download-save-0","otStore":"playlist-dowload-default-playlist-dowload-download-save-log-output_OT","hbStore":"playlist-dowload-default-playlist-dowload-download-save-log-output_PROCESSORS","OT":"playlist-dowload-default-playlist-dowload-download-save-log-output_OT","processorEntity":"playlist-dowload-download-save-0","error":"nats: key not found"}
{"level":"info","ts":1670137326.763254,"logger":"numaflow.MapUDF-processor","caller":"publish/publisher.go:174","msg":"Publishing Heartbeat ticker started","vertex":"playlist-dowload-download-save","entityID":"playlist-dowload-download-save-0","otStore":"playlist-dowload-default-playlist-dowload-download-save-log-output_OT","hbStore":"playlist-dowload-default-playlist-dowload-download-save-log-output_PROCESSORS"}
{"level":"info","ts":1670137326.7648904,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7649817,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.767186,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7672753,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7676594,"logger":"numaflow.MapUDF-processor","caller":"publish/publisher.go:61","msg":"Creating a new watermark publisher","vertex":"playlist-dowload-download-save","entityID":"playlist-dowload-download-save-0","otStore":"playlist-dowload-default-playlist-dowload-download-save-log-download-error-output_OT","hbStore":"playlist-dowload-default-playlist-dowload-download-save-log-download-error-output_PROCESSORS"}
{"level":"warn","ts":1670137326.7680478,"logger":"numaflow.MapUDF-processor","caller":"publish/publisher.go:154","msg":"Unable to load latest watermark from ot store (failed to get value from ot store)","vertex":"playlist-dowload-download-save","entityID":"playlist-dowload-download-save-0","otStore":"playlist-dowload-default-playlist-dowload-download-save-log-download-error-output_OT","hbStore":"playlist-dowload-default-playlist-dowload-download-save-log-download-error-output_PROCESSORS","OT":"playlist-dowload-default-playlist-dowload-download-save-log-download-error-output_OT","processorEntity":"playlist-dowload-download-save-0","error":"nats: key not found"}
{"level":"info","ts":1670137326.7681432,"logger":"numaflow.MapUDF-processor","caller":"publish/publisher.go:174","msg":"Publishing Heartbeat ticker started","vertex":"playlist-dowload-download-save","entityID":"playlist-dowload-download-save-0","otStore":"playlist-dowload-default-playlist-dowload-download-save-log-download-error-output_OT","hbStore":"playlist-dowload-default-playlist-dowload-download-save-log-download-error-output_PROCESSORS"}
{"level":"info","ts":1670137326.769831,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7699223,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7723927,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.7724729,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.774096,"logger":"numaflow.MapUDF-processor","caller":"jetstream/default_jetstream_client.go:74","msg":"Nats: connected to nats server","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137326.774153,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:86","msg":"Starting Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2882528,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2882752,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.288271,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2883022,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2883244,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2883012,"logger":"numaflow.MapUDF-processor","caller":"jetstream/kv_watch.go:128","msg":"stopping WatchAll","vertex":"playlist-dowload-download-save","pipeline":"playlist-dowload","kvBucketName":"playlist-dowload-default-playlist-dowload-list-playlist-download-save_PROCESSORS","watcher":"playlist-dowload-default-playlist-dowload-list-playlist-download-save_PROCESSORS"}
{"level":"info","ts":1670137335.2883315,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2883224,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2883458,"logger":"numaflow.MapUDF-processor","caller":"jetstream/kv_watch.go:128","msg":"stopping WatchAll","vertex":"playlist-dowload-download-save","pipeline":"playlist-dowload","kvBucketName":"playlist-dowload-default-playlist-dowload-list-playlist-download-save_OT","watcher":"playlist-dowload-default-playlist-dowload-list-playlist-download-save_OT"}
{"level":"info","ts":1670137335.2883255,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2883337,"logger":"numaflow.MapUDF-processor","caller":"jetstream/in_cluster_jetstream_client.go:109","msg":"Exited Nats JetStream auto reconnection daemon...","vertex":"playlist-dowload-download-save"}
{"level":"info","ts":1670137335.2897851,"logger":"numaflow.MapUDF-processor","caller":"jetstream/kv_watch.go:134","msg":"WatchAll successfully stopped","vertex":"playlist-dowload-download-save","pipeline":"playlist-dowload","kvBucketName":"playlist-dowload-default-playlist-dowload-list-playlist-download-save_OT","watcher":"playlist-dowload-default-playlist-dowload-list-playlist-download-save_OT"}
{"level":"info","ts":1670137335.2921677,"logger":"numaflow.MapUDF-processor","caller":"jetstream/kv_watch.go:134","msg":"WatchAll successfully stopped","vertex":"playlist-dowload-download-save","pipeline":"playlist-dowload","kvBucketName":"playlist-dowload-default-playlist-dowload-list-playlist-download-save_PROCESSORS","watcher":"playlist-dowload-default-playlist-dowload-list-playlist-download-save_PROCESSORS"}
Error: failed on UDF readiness check, failed on readiness check: context canceled
Usage:
  numaflow processor [flags]

Flags:
  -h, --help                 help for processor
      --isbsvc-type string   ISB Service type, e.g. jetstream
      --type string          Processor type, 'source', 'sink' or 'udf'

panic: failed on UDF readiness check, failed on readiness check: context canceled

goroutine 1 [running]:
github.com/numaproj/numaflow/cmd/commands.Execute()
	/home/runner/work/numaflow/numaflow/cmd/commands/root.go:33 +0x45
main.main()
	/home/runner/work/numaflow/numaflow/cmd/main.go:24 +0x17
```

**Environment (please complete the following information):**

- Kubernetes: kind v0.11.1 go1.17.1 linux/amd64
- Numaflow: v0.6.4
- Numaflow-python: v0.2.6 (pynumaflow = "0.2.6")

**Additional context**
- Logs from udf shows that msg is processed correctly.
- Issue does not occur when batch size is set to 1
```
    limits: 
      readBatchSize: 1
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
I believe this happens when the batch size is not smaller than the number of threads of the python SDK gRPC server. One workaround is to reduce the batch size, meanwhile check what can be enhanced from the SDK side.

**Comment by ab93** [comment]
Thanks for the issue @alexanghh . Can you try reducing from the default `readBatchSize` and check? I believe it should work with`readBatchSize` <= 50.

**Comment by alexanghh** [comment]
@ab93 I tested the following readBatchSize:
- 1 - ok 
- 10 - ok
- 20 - not ok 
- 30 - not ok
- 40 - not ok
- 50 - not ok

**Comment by vigith** [comment]
@kohlisid, let's try using asyncio Map UDF.

**Comment by vigith** [comment]
We have added asyncio map and also multi-proc map added to 0.4.x SDK release. This problem should no longer be applicable if we are to use either of the above approaches.
